vlm:
  model_name: qwen/qwen3.5-397b-a17b
  api_key: xxxxx
  base_url: xxxxx
  max_tokens: 1024
  temperature: 0

env:
  serial_no: emulator-5554

max_steps: 25
num_latest_screenshots: 3
max_action_retry: 5
