# This is the config file for the Macro1 agent framework.
# Choose the `MultiAgent` type to use it.
# '''
# import macro1
# config_path = "config/macro1.yaml"
# agent = macro1.Agent.from_params(dict(
#       type="MultiAgent",
#       config_path=config_path,
#     ))
# '''


vlm:
  model_name: qwen2.5-vl-72b-instruct
  api_key: xxxxx
  base_url: xxxxx
  max_tokens: 1024
  temperature: 0

env:
  # The serial_no of your android virtual / physical devices, use `adb devices` to find it.
  serial_no: xxxxx

operator:
  enabled: true
  name: Operator
  prompt_config: operator.yaml
  # # To enable proactive exlporation, enable the following config.
  # # See macro1/utils/proactive_exploration/README.md for more details.
  # knowledge: 
  #   explored_knowledge_path: <path-to-explored-knowledge-json-file>

answer_agent:
  enabled: true
  name: AnswerAgent
  prompt_config: answer_agent.yaml
  # # To enable proactive exlporation, enable the following config.
  # # See macro1/utils/proactive_exploration/README.md for more details.
  # knowledge: 
  #   explored_knowledge_path: <path-to-explored-knowledge-json-file>

reflector:
  enabled: true

trajectory_reflector:
  enabled: true

global_reflector:
  enabled: true

progressor:
  enabled: true

# # To enable Reflection-on-Demand, enable the following config.
# # You may need to adjust the reflection threshold.
# reflect_on_demand: true
# logprob_threshold: -0.001
