# Macro1 ReAct Agent configuration
#
# Usage:
#   from macro1.agents import Agent
#   agent = Agent.from_params(dict(type="ReAct", config_path="configs/macro1.yaml"))

vlm:
  model_name: qwen/qwen3.5-397b-a17b
  api_key: xxxxx
  base_url: xxxxx
  max_tokens: 1024
  temperature: 0

env:
  # The serial_no of your android virtual / physical devices, use `adb devices` to find it.
  serial_no: xxxxx

max_steps: 10
num_latest_screenshots: 3
max_action_retry: 5
