name: Macro1ReAct

agent:
    name: Macro1Agent
    args:
      agent_config:

        type: ReAct

        vlm:
          model_name: qwen/qwen3.5-397b-a17b
          api_key: xxxxx
          base_url: xxxxx
          max_tokens: 1024
          temperature: 0

        max_steps: 25
        num_latest_screenshots: 3
        max_action_retry: 5


task:
  class: Macro1_AutoTest
  args:
    save_dir: "./logs/evaluation_macro1"
    max_rounds: 25
    request_interval: 3

eval:
  avd_name: Pixel_7_Pro_API_33
  avd_log_dir: ./logs/evaluation
  docker: True
  docker_args:
    image_name: android_eval:latest
    port: 6060
